[package]
name = "privacy-channels"
version = "3.0.0"
authors = ["Ignacio Palacios"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/NachoPal/substrate-private-channels"

[dependencies]
log = { version = '0.4.11'}
serde = { features = ['derive'], optional = true, version = '1.0.101' }
sp-std = { default-features = false, version = '3.0.0', path = "../../../../primitives/std"}
sp-runtime = { default-features = false, version = '3.0.0', path = "../../../../primitives/runtime" }
sp-core = { default-features = false, version = '3.0.0', path = "../../../../primitives/core" }
frame-support = { default-features = false, version = '3.0.0', path = "../../../../frame/support" }
frame-system = { default-features = false, version = '3.0.0', path = "../../../../frame/system" }
sp-io = { default-features = false, version = '3.0.0', path = "../../../../primitives/io" }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
crypto-box = {package = "crypto_box", version = "0.5.0", features=["u32_backend"], default-features = false}
salsa20 = {package = "salsa20", version = "0.7.2", default-features = false}
generic-array = {package = "generic-array", version = "0.14.4", default-features = false}

[features]
default = ['std']
std = [
    'codec/std',
    'sp-std/std',
    'sp-runtime/std',
    'frame-support/std',
    'sp-core/std',
    'sp-io/std',
    'frame-system/std',
    'serde',
	'crypto-box/std'
]
