[package]
name = "private-channels"
version = "3.0.0"
authors = ["Ignacio Palacios"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/NachoPal/substrate-private-channels"

[dependencies]
hex = { version = "0.4", default-features = false }
log = { version = '0.4.11'}
serde = { version = "1.0.101", default-features = false, features = ['derive'] }
sp-application-crypto = { version = "3.0.0", default-features = false, path = "../../../../primitives/application-crypto" }
sp-std = { default-features = false, version = '3.0.0', path = "../../../../primitives/std"}
sp-runtime = { default-features = false, version = '3.0.0', path = "../../../../primitives/runtime" }
sp-core = { default-features = false, version = '3.0.0', path = "../../../../primitives/core" }
frame-support = { default-features = false, version = '3.0.0', path = "../../../../frame/support" }
frame-system = { default-features = false, version = '3.0.0', path = "../../../../frame/system" }
sp-io = { default-features = false, version = '3.0.0', path = "../../../../primitives/io" }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
serde_json = { version = '1.0.64', default-features = false, features = ['alloc'] }
# serde_bytes = { version = "0.11", default-features = false, features = ['alloc'] }
# sodiumoxide = {package = "sodiumoxide", version = "0.2.6", default-features = true}

[features]
default = ['std']
std = [
    'codec/std',
    'sp-std/std',
    'sp-runtime/std',
    'frame-support/std',
    'sp-core/std',
    'sp-io/std',
    'frame-system/std',
	'hex/std'
	# 'sodiumoxide/std',
]
